title: VegaWiki
description: Vega Institute Foundation
theme: just-the-docs

url: https://vegawiki.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
