title: VegaWiki
description: Vega Institute Foundation
theme: just-the-docs

url: https://vegawiki.github.io

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
