title: VegaWiki
description: Wiki for Vega Courses
theme: just-the-docs

url: https://vegawiki.github.io

aux_links:
  GitHub Repository: https://github.com/vegawiki/vegawiki.github.io

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

just_the_docs:
  - collections:
      - docs:
        name: Docs
        nav_fold: true